name: '自动填报晨午晚检 --roccoshi'

on:
  push:
  schedule:
     - cron: '5 */2 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        presist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: 石
      run: |
        python ./upload.py -n 1 -u ${{ secrets.CHENWUJIAN_USERNAME }} -p ${{ secrets.CHENWUJIAN_PASSWORD}} -f ./data/upload.txt
    - name: 王
      run: |
        python ./upload.py -n 1 -u ${{ secrets.USER_TWO }} -p ${{ secrets.PASS_TWO }} -f ./data/upload.txt
    - name: 汤
      run: |
        python ./upload.py -n 1 -u ${{ secrets.USER_THREE }} -p ${{ secrets.PASS_THREE }} -f ./data/upload.txt
    - name: 李
      run: |
        python ./upload.py -n 1 -u ${{ secrets.USER_FOUR }} -p ${{ secrets.PASS_FOUR }} -f ./data/upload.txt
    - name: 张
      run: |
        python ./upload.py -n 1 -u ${{ secrets.USER_FIVE }} -p ${{ secrets.PASS_FIVE }} -f ./data/upload.txt
